include:
  - project: devops/devops-ci-templates
    file: templates/gitlab-ci-documentation.yml
  - project: devops/devops-ci-templates
    file: templates/gitlab-ci-pypi.yml

stages:
  - build-doc
  - build-package

build-documentation:
  before_script:
    - pip install git+http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.fiber-resources.com/mongodb/datautils.git
    - pip install git+http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.fiber-resources.com/mongodb/mongoutils.git
    - pip install git+http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.fiber-resources.com/mongodb/mongomanager.git