[project]
name = "mongoreader"
version = "1.4.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Francesco Garrisi", email = "francesco.garrisi@fiber-resources.com" }
]
requires-python = ">=3.11"
dependencies = [
    "bson>=0.5.10",
    "datautils",
    "matplotlib>=3.10.1",
    "mongomanager",
    "mongoutils",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
]

[project.scripts]
mongoreader = "mongoreader:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
mongoutils = { git = "ssh://git@gitlab.fiber-resources.com/mongodb/mongoutils.git", branch = "uv-packaging" }
mongomanager = { git = "ssh://git@gitlab.fiber-resources.com/mongodb/mongomanager.git", branch = "uv-packaging" }
datautils = { git = "ssh://git@gitlab.fiber-resources.com/mongodb/datautils.git", branch = "uv-packaging" }
